name: Lighthouse CI

on:
  push:
    branches: [main, rockited_dev, staging]
  pull_request:
    branches: [main, rockited_dev, staging]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"

      - name: Run Lighthouse CI
        run: npm run perf:lighthouse
